const eventsData = [
    {
        id: 1,
        name: "Web3 Global Conference",
        date: "Saturday, October 29, 2024",
        time: "9:00am",
        location: "The Zone",
        imageUrl: "/images/event3.svg",
        dateUrl: "/images/calendar.svg",
        timeUrl: "/images/time.svg",
        locationUrl: "/images/location.svg",
        category: "Offline",
        price: "₦5,000.00",
        free: false,
    },
    {
        id: 2,
        name: "The Development of Art",
        date: "Wednesday, September 18, 2024",
        time: "11:00 AM",
        location: "Online",
        imageUrl: "/images/event2.svg",
        dateUrl: "/images/calendar.svg",
        timeUrl: "/images/time.svg",
        locationUrl: "/images/location.svg",
        category: "Online",
        price: "Free",
        free: true,
    },
    {
        id: 3,
        name: "The Future is Seraph",
        date: "Saturday, September 21, 2024",
        time: "10:00 AM",
        location: "Solution area",
        imageUrl: "/images/event1.svg",
        dateUrl: "/images/calendar.svg",
        timeUrl: "/images/time.svg",
        locationUrl: "/images/location.svg",
        category: "Offline",
        price: "₦1,000.00",
        free: false,
    },
    {
        id: 4,
        name: "Web3 Global Conference",
        date: "Saturday, October 29, 2024",
        time: "9:00am",
        location: "The Zone",
        imageUrl: "/images/event3.svg",
        dateUrl: "/images/calendar.svg",
        timeUrl: "/images/time.svg",
        locationUrl: "/images/location.svg",
        category: "Offline",
        price: "₦5,000.00",
        free: false,
    },
    {
        id: 5,
        name: "The Development of Art",
        date: "Wednesday, September 18, 2024",
        time: "11:00 AM",
        location: "Online",
        imageUrl: "/images/event2.svg",
        dateUrl: "/images/calendar.svg",
        timeUrl: "/images/time.svg",
        locationUrl: "/images/location.svg",
        category: "Online",
        price: "Free",
        free: true,
    },
    {
        id: 6,
        name: "The Future is Seraph",
        date: "Saturday, September 21, 2024",
        time: "10:00 AM",
        location: "Solution area",
        imageUrl: "/images/event1.svg",
        dateUrl: "/images/calendar.svg",
        timeUrl: "/images/time.svg",
        locationUrl: "/images/location.svg",
        category: "Offline",
        price: "₦1,000.00",
        free: false,
    },
    {
        id: 7,
        name: "Web3 Global Conference",
        date: "Saturday, October 29, 2024",
        time: "9:00am",
        location: "The Zone",
        imageUrl: "/images/event3.svg",
        dateUrl: "/images/calendar.svg",
        timeUrl: "/images/time.svg",
        locationUrl: "/images/location.svg",
        category: "Offline",
        price: "₦5,000.00",
        free: false,
    },
    {
        id: 8,
        name: "The Development of Art",
        date: "Wednesday, September 18, 2024",
        time: "11:00 AM",
        location: "Online",
        imageUrl: "/images/event2.svg",
        dateUrl: "/images/calendar.svg",
        timeUrl: "/images/time.svg",
        locationUrl: "/images/location.svg",
        category: "Online",
        price: "Free",
        free: true,
    },
    {
        id: 9,
        name: "The Future is Seraph",
        date: "Saturday, September 21, 2024",
        time: "10:00 AM",
        location: "Solution area",
        imageUrl: "/images/event1.svg",
        dateUrl: "/images/calendar.svg",
        timeUrl: "/images/time.svg",
        locationUrl: "/images/location.svg",
        category: "Offline",
        price: "₦1,000.00",
        free: false,
    },
    
    // Add more events here
];

export default eventsData;
